config/routes.rb
Bkngjobs::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"
  match 'jobs/updatedb' => 'jobs#updatedb'
  match 'jobs/open' => 'jobs#open'
  match 'jobs/closed' => 'jobs#closed'
  match 'stats' => 'stats#index'

  resources :jobs

  root :to => "home#index"
end

app/models/dbsnap.rb
class Dbsnap
  include Mongoid::Document
  include Mongoid::Timestamps

  field :open, type: Integer
  field :closed, type: Integer


end

app/models/job.rb
require 'resque/errors'

class StreamStart

end

class ImportJobs
  @queue = :jobs

  def self.perform
    Job.fetch_jobs
    Job.check_if_removed
  rescue Resque::TermException
  end
end

class Job
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :joblink, type: String
  field :department, type: String
  field :city, type: String
  field :type, type: String
  field :jobid, type: String
  field :burb, type: String
  field :loc_country, type: String
  field :closed_at, type: Time
  field :track_code,type: String

  index({ jobid: 1 }, { unique: true })

  scope :open, where(:closed_at => nil)
  scope :closed, ne(:closed_at=>nil)

  def self.fetch_jobs
    agent     = Mechanize.new
    page      = agent.get('http://www.booking.com/jobs.html')
    countries = page.link_with(:text => "See all jobs").click.search("ul.countries li a").map(&:text)

    jobs = page.link_with(:text => "See all jobs")
    countries.each do |country|
      jobs.click.link_with(:text => country).click.links_with(:href=>/job_id/).each do |element|
        jb = element.click.search("div#job_detail p.meta").text.split("\n")
        j             = Job.new
        j.loc_country = country
        #j.title       = element.children[1].text
        j.title       = element.text
        j.joblink     = element.href
        #j.joblink     = element.children[1]['href']
        j.jobid       = element.href.scan(/\d+/).last
        #j.jobid       = element.children[1]['href'].scan(/\d+/).last
        #j.city        = element.children[3].text.scan(/\w+/).last
        j.city        = jb[1]
        #j.burb        = element.children[3].text
        j.type        = jb[2]
        #j.type        = element.children[3].text.scan(/\b\w+\-\w+\/\w+\b/).first
        j.department  = jb[3]

        #j.department  = element.children[3].text.scan(/^(?:.+)(?=\s+\b\w+\-\w+\/\w+\b)/).first
        j.save
      end
    end
    create_snapshot

  end

  def self.create_snapshot
    sn=Dbsnap.new
    sn.open=Job.open.count
    sn.closed=Job.closed.count
    sn.save
  end

  def self.check_if_removed
    agent      = Mechanize.new
    page       = agent.get('http://www.booking.com/jobs.html')
    countries  = page.link_with(:text => "See all jobs").click.search("ul.countries li a").map(&:text)
    jobs       = page.link_with(:text => "See all jobs")
    remotejobid=[]
    countries.each do |country|
      remotejobid << jobs.click.link_with(:text => country).click.search("div#country_or_category ul li").map { |i| i.children[1]['href'].scan(/\d+/).last }

    end

    localjobid = Job.where(:closed_at => nil).map(&:jobid)
    closed     = localjobid - remotejobid.flatten
    closed.each { |job_id| p = Job.where(:jobid => job_id).first; p.closed_at=Time.now; p.save }
  end

  def self.async_import
    Resque.enqueue(ImportJobs)
  end


end

app/models/location.rb
class Location
  include Mongoid::Document
  field :city, type: String
  field :country, type: String
  field :lat, type: Float
  field :lng, type: Float

  index({ city: 1 }, { unique: true })



end

app/models/stat.rb
class Stat
  include Mongoid::Document


  def by_department
    sum = Hash.new(0)
    Job.all.map(&:department).each{|i| sum.store(i,sum[i]+1)}
    return sum
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  def open
    @jobs = Job.open.desc(:created_at)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end


  end

  def updatedb
    Job.async_import
    flash[:notice]="Resque worker is doing this now!"
    redirect_to jobs_path
  end

  def closed
    @jobs=Job.closed

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    chart_data = Stat.new.by_department.sort_by { |k, v| v }.reverse
    @chart     = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(:type => 'pie')
      f.series(:name => 'Jobs so far', :data => chart_data.to_a)
      f.title(:text => "Job generation by department")
      #f.plotOptions(:pie=>{:size=>'100%'})
      #f.xAxis(:labels=>{:rotation=>-55 , :align => 'right'},:categories=>chart_data.map{|key,value| key })
    end

    snapshots       = Dbsnap.all
    @open_job_dates = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(:type => 'line', :width => 520)
      f.series(:data => snapshots.map(&:open))
      f.xAxis(:labels => { :rotation => -65, :align => 'right' }, :categories => snapshots.map { |i| i.created_at.strftime(format='%D %R') })
      f.title(:text => "Open Jobs by date")
    end

    closed_list = Dbsnap.all.map(&:closed)
    df          = []
    df << closed_list[0]
    (2..closed_list.count-1).each do |d|
      df << closed_list[d] - closed_list[(d - 1)]
      df.compact
    end
    df << closed_list[closed_list.count]

    @closed_job_dates = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(:type => 'line', :width => 520)
      f.series(:data => df.compact)
      #f.series(:data=>snapshots.map(&:closed))
      f.xAxis(:labels => { :rotation => -65, :align => 'right' }, :categories => snapshots.map { |i| i.created_at.strftime(format='%D %R') })
      f.title(:text => "Closed Jobs by date")
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :joblink
    = f.text_field :joblink
  .field
    = f.label :department
    = f.text_field :department
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :jobid
    = f.text_field :jobid
  .actions
    = f.submit 'Save'

app/views/jobs/_idx.html.haml
%h3 #{title} Jobs

%table.datatable.table.table-hover
  %thead
    %tr
      %th Title
      %th Joblink
      %th Department
      %th Open since
      %th Closed at
      %th City
      %th Type
      -#%th Jobid
      -#%th
      -#%th
      -#%th
  %tbody
    - @jobs.each do |job|
      %tr
        %td
          %span= link_to job.title,job,:class=>'btn'
        %td= link_to("GoTO","http://www.booking.com/jobs.en-us.html?st=details&job_id=#{job.jobid}")
        %td= job.department
        - if Time.now.to_date-job.created_at.to_date < 5 and job.created_at.nil?
          %td
            = job.created_at.to_date
            %span
              %small= "new!"
        - else
          %td= job.created_at.to_date
        - if job.closed_at.nil?
          %td
            %span.label.label-success= "Still Open"
        - else
          %td
            %span.label.label-warning= job.closed_at.to_date
        -#%td= job.closed_at.nil? ? "Still open" : job.closed_at.to_date
        %td= job.city
        %td= job.type
        -#%td= job.jobid
        -#%td= link_to 'Show', job
        -#%td= link_to 'Edit', edit_job_path(job)
        -#%td= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }
  %tfoot      

%br

-#= link_to 'New Job', new_job_path
-#:javascript
-#  $('.datatable').dataTable({
-#  "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
-#  "sPaginationType": "bootstrap"
-#  });
:javascript
  $('.datatable').dataTable({
    "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
    "sPaginationType": "bootstrap",
    "iDisplayLength": 30
  });

app/views/jobs/_index.html.haml
%h3 #{title} Jobs

%table.datatable.table.table-hover
  %thead
    %tr
      %th Title
      %th Joblink
      %th Department
      %th Open since
      %th Closed at
      %th City
      %th Type
      -#%th Jobid
      -#%th
      -#%th
      -#%th
  %tbody
    - @jobs.each do |job|
      %tr
        %td
          %span= link_to job.title,job,:class=>'btn'
        %td= link_to("GoTO","http://www.booking.com/jobs.en-us.html?st=details&job_id=#{job.jobid}")
        %td= job.department
        - if Time.now.to_date-job.created_at.to_date < 5 and job.created_at.nil?
          %td
            = job.created_at.to_date
            %span
              %small= "new!"
        - else
          %td= job.created_at.to_date
        - if job.closed_at.nil?
          %td
            %span.label.label-success= "Still Open"
        - else
          %td
            %span.label.label-warning= job.closed_at.to_date
        -#%td= job.closed_at.nil? ? "Still open" : job.closed_at.to_date
        %td= job.city
        %td= job.type
        -#%td= job.jobid
        -#%td= link_to 'Show', job
        -#%td= link_to 'Edit', edit_job_path(job)
        -#%td= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }
  %tfoot      

%br

-#= link_to 'New Job', new_job_path
-#:javascript
-#  $('.datatable').dataTable({
-#  "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
-#  "sPaginationType": "bootstrap"
-#  });
:javascript
  $('.datatable').dataTable({
    "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
    "sPaginationType": "bootstrap",
    "iDisplayLength": 100
  });

app/views/jobs/closed.html.haml
= render 'idx' ,:title => "Closed"

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
= render 'idx', :title => "History of"

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/open.html.haml
= render 'idx', :title => "Open"

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @job.title
%p
  %b Joblink:
  = @job.joblink
%p
  %b Department:
  = @job.department
%p
  %b City:
  = @job.city
%p
  %b Type:
  = @job.type
%p
  %b Jobid:
  = @job.jobid

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "All Jobs", jobs_path, :class => 'brand'
%ul.nav.nav-pills
  %li
    = link_to "Open",jobs_open_path
  %li
    = link_to "Closed", jobs_closed_path
  %li
    = link_to "Statistics",stats_path
  %li
    = link_to "Resque","/resque",:style=>"float:right;",:target=>"_blank"
= link_to "Update",jobs_updatedb_path, :class=>'btn',:style=>"float:right;"

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Bkngjobs"
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/stats/index.html.haml
%lines
  = high_chart("jobs_id",@open_job_dates)
  = high_chart("cjobs_id",@closed_job_dates)
= high_chart("my_id", @chart)